name: Publish Scala Package

on:
  push:
    branches: [ "publish" ]
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # You can also use 'zulu', 'temurin', etc.
          java-version: '21'  # Updated to use Java 21

      - name: Cache SBT dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Build and publish
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_PACKAGES }}
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
        run: sbt publish
